### ISSUE TITLE
How to enable cluster_radius_plugin on a map?

### ISSUE THREAD

**Issue by ano1** [strk/dolpp#1]
I located your module after reading this thread on d.o. http://drupal.org/node/884662 . Can someone please tell me how to enable the cluster_radius_plugin on my map? I have checked every OpenLayers setting page I can think of, but fail to see any new clustering options. I can see in cluster_radius_plugin.inc, what fields I should look for in the UI, but can't locate them. Thanks in advance for the help.

**Comment by strk** [comment]
It should be in the style editor, giving you the option of selecting the plugin for the pointRadius property.

**Comment by ano1** [comment]
Hi again, thanks for the reply but I am still at a loss. Do you mean: admin/build/openlayers/styles/{STYLE-NAME}/edit  or am I missing another style editing screen?

**Comment by strk** [comment]
Yes, that's the page.

Try enabling the test module coming with drupal opnelayers module.
That module should install style plugins too (for random point radius and the like).
If the test module works and dolpp doesn't there might be a recent compatibility issue

**Comment by ano1** [comment]
Thanks for the test criteria. Sadly, I see no change in the style editing screen when I enable the openlayer test, dolpp or OL+ modules. I am running OpenLayers 6.x-2.0-alpha10, do I need a different version? Thanks again for your support.

**Comment by strk** [comment]
If enabling the OL test makes no difference you'd better continue the conversation on the OL tracker.

<rant> not having your email is extremely annoying (forces me to fire up the browser for every response). Nothing against yourself, but I think github should give the email of someone asking me something. I see no alternative than giving my or yours email on this public forum otherwise... </rant>

**Comment by ano1** [comment]
For those reading this who might have a similar problem, the solution was upgrading to OpenLayers 6.x-2.x-dev. Thanks to strk, this step has now been reflected in dolpp's README.

**Comment by strk** [comment]
urhm.. didn't you say -alpha10 was not enough and you had to upgrade to -dev?

**Comment by ano1** [comment]
Good catch, I accidentally pasted the wrong version, post has been updated.
